version: '3.9'

services:
  app:
    build: .
    restart: always
    depends_on:
      - postgredb
    volumes:
      - ./build:/src/build
      - ./static:/src/static
      - ./media:/src/media
  postgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
  nginx:
      image: nginx:1.19.7
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./static:/project/static
        - ./media:/project/media
        - ./build:/project/build
        - ./nginx_logs:/var/log/nginx
      depends_on:
        - app
